### ISSUE TITLE
Revert "EventLog: Disable event writing in production builds"

### ISSUE THREAD

**Issue by Oblivion130** [yaap/frameworks_base_old#23]
* This commit is incorrect because of two reasons. First, public API should not be modified in any case. Second, there are actually apps using event log feature to perform black magic. For example, Brevent
   (https://play.google.com/store/apps/details?id=me.piebridge.brevent)
   checks event log to determine when apps are moved into background and kill them after some time accordingly.
Don't konw how to pull request but this one made some problems,please revert it.
 https://github.com/yaap/frameworks_base/commit/d89fd171f7d43ea5c9c930a2418aadb58394199e

**Comment by poad42** [comment]
Is this api documented publicly for app use?

**Comment by Oblivion130** [comment]
> Is this api documented publicly for app use?

I think yes？

**Comment by idoybh** [comment]
https://github.com/yaap/frameworks_base/commit/98d1c9d046a7a494c67f70074b4feafe29e6d157 

thanks @ZeroWickD, next time do a PR ;)
